name: Build Playnite Extension

# Trigger this workflow manually
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Check out the repository at the specified commit.
      - name: Checkout repository at commit 50ed2ef2bebd07f3635fd4c4e003980513154f2f
        uses: actions/checkout@v4
        with:
          repository: Koriebonx98/Main-Stuff
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: 50ed2ef2bebd07f3635fd4c4e003980513154f2f

      # Ensure MSBuild is in the PATH.
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      # Restore NuGet packages for the solution.
      - name: Restore NuGet packages
        run: nuget restore "Playnite Addons/PC_GAMES_Local/PC_GAMES_Local.sln"

      # Build and package the Playnite extension.
      - name: Build and Package Playnite Extension
        run: msbuild "PC_GAMES_Local.csproj" /t:Package /p:Configuration=Release
        working-directory: "Playnite Addons/PC_GAMES_Local"

      # Upload the generated .pext file as an artifact.
      - name: Upload Playnite Extension Artifact
        uses: actions/upload-artifact@v4
        with:
          name: PC_GAMES_Local.pext
          path: "Playnite Addons/PC_GAMES_Local/bin/Release/PC_GAMES_Local.pext"
