name: Build Playnite Extension

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Checkout the repository at the specified commit.
      - name: Checkout repository at commit 50ed2ef2bebd07f3635fd4c4e003980513154f2f
        uses: actions/checkout@v4
        with:
          repository: Koriebonx98/Main-Stuff
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: 50ed2ef2bebd07f3635fd4c4e003980513154f2f

      # Setup MSBuild on the Windows runner.
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      # Restore NuGet packages.
      - name: Restore NuGet packages
        run: nuget restore "Playnite Addons/PC_GAMES_Local/PC_GAMES_Local.sln"

      # Build the Playnite extension project.
      - name: Build Playnite Extension
        run: msbuild "PC_GAMES_Local.csproj" /p:Configuration=Release
        working-directory: "Playnite Addons/PC_GAMES_Local"

      # Manually package the extension by zipping the necessary files.
      - name: Package Playnite Extension
        shell: pwsh
        run: |
          # Set the package output path.
          $packagePath = "bin/Release/PC_GAMES_Local.pext"
          if (Test-Path $packagePath) { Remove-Item $packagePath }
          
          # Choose the files to package. Typically, a Playnite extension needs:
          # - extension.yaml (the manifest)
          # - icon.png (the icon)
          # - the compiled binaries from bin/Release (e.g., PC_GAMES_Local.dll)
          #
          # Adjust the list below if you want to include/exclude files.
          $filesToInclude = @("extension.yaml", "icon.png", "bin/Release/*")
          
          # Create a ZIP archive and output it as a .pext file.
          Compress-Archive -Path $filesToInclude -DestinationPath $packagePath -Force
        working-directory: "Playnite Addons/PC_GAMES_Local"

      # Upload the resulting .pext file as an artifact.
      - name: Upload Playnite Extension Artifact
        uses: actions/upload-artifact@v4
        with:
          name: PC_GAMES_Local.pext
          path: "Playnite Addons/PC_GAMES_Local/bin/Release/PC_GAMES_Local.pext"
